### ISSUE TITLE
transferMultiple should check unlockedTokens like function transfer

### ISSUE THREAD

**Issue by jjnetcn** [Fantom-foundation/tokensale#1]
transferMultiple should call 
require(_amounts[i] <= unlockedTokensInternal(msg.sender));
before
super.transfer(_addresses[i], _amounts[i]);

**Comment by MKong** [comment]
Hi jjnetcn.

Thanks for identifying the issue. We have fixed as required.

Please feel free to reach out to me on Telegram at @mkong888.

Thanks,
MIchael

**Comment by jjnetcn** [comment]
Ok,  i pm u message just now, with my telegram username @jjnetcn
